#Reference https://github.com/andresaaap/simple-html-rolling-update-kubernetes/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-anh
  labels:
    app: deploy-anh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-anh
      role: rolling-update
  template:
    metadata:
      labels:
        app: deploy-anh
    spec:
      containers:
        - image: anhanh2212/buildcusnginx:v1.0.0
          name: newcontainer
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
