apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-anh
  labels:
    app: deploy-anh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-anh
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deploy-anh
    spec:
      containers:
        - image: anhanh2212/buildcusnginx:v1.0.0
          name: deploy-anh
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              
      imagePullSecrets:
        - name: regcred