#Reference https://github.com/andresaaap/simple-html-rolling-update-kubernetes/

apiVersion: v1
kind: Service
metadata:
  name: service-anh
  labels: 
    app: service-anh
spec:
  selector:
    app: deploy-anh
  ports:
    - port: 8000
      targetPort: 80
  type: LoadBalancer