apiVersion: v1
kind: Service
metadata:
  name: rolling-service
  labels: 
    app: rolling-service
spec:
  selector:
    app: rolling-app
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer