apiVersion: v1
kind: Service
metadata:
  name: service-anh
  labels: 
    app: service-anh
spec:
  selector:
    app: deploy-anh
  ports:
    - name: http
      port: 80
      nodePort: 30001
      protocol: TCP
  type: LoadBalancer