# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
# Reference https://github.com/andresaaap/cicd-only-deploying-circleci/blob/main/.circleci/config.yml
version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

jobs: 
  build-lint:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 

  push-image-to-dockerhub:
    docker:
      - image: cimg/python:3.10
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build new Docker Image
          command: |
            echo "Build image and add a descriptive tag"
            docker build --tag=buildcusnginx .
            docker image ls
      - run:
          name: Public Docker Image to Dockerhub
          command: |
            echo "Authenticate & tag"
            docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
            docker tag buildcusnginx $DOCKERHUB_USERNAME/buildcusnginx:v1.0.0
            echo "Push image to a docker repository"
            docker push $DOCKERHUB_USERNAME/buildcusnginx:v1.0.0

  create-cluster:
    docker:
      - image: python:3.7.3-stretch
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            pip install awscli
            # apt-get update && sudo apt-get install -yy less
            # curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            # unzip awscliv2.zip
            # sudo ./aws/install
            aws --version
      - run:
          name: Check existing cluster
          command: |
            # export OLD_CLUSTER=$(aws eks list-clusters --query 'clusters' --output text | tr '\t' '\n' | grep << parameters.cluster-name >>)
            # echo OLD_CLUSTER: "${OLD_CLUSTER}"

            # if [ "$OLD_CLUSTER" == << parameters.cluster-name >> ]; then
            #   echo "Found OLD_CLUSTER !!"
            #   circleci step halt
            # else
            #   echo "Not Found OLD_CLUSTER !!"
            # fi
            CLUSTER=nginxcustomcluster
            CHECK_NAME=$(aws eks list-clusters | jq -r ".clusters" | grep $CLUSTER || true)
            if [ "$CHECK_NAME" != "" ]; then
              echo "There is already a cluster by this name;"
              exit 1
            else
              echo "No cluster by this name $CLUSTER"
            fi
      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>

  # list-cluster:
  #   docker:
  #     - image: python:3.7.3-stretch
  #   parameters:
  #     cluster-name:
  #       description: |
  #         Name of the EKS cluster
  #       type: string
  #   steps:
  #     - checkout
  #     - kubernetes/install
  #     - aws-eks/update-kubeconfig-with-authenticator:
  #         cluster-name: << parameters.cluster-name >>
  #     - run:
  #         name: List kubernetes pods
  #         command: |
  #           kubectl get deploy,rs,svc,pods
  deploy-cluster:
    docker:
      - image: python:3.7.3-stretch
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl create deploy $DOCKERHUB_USERNAME --image=$DOCKERHUB_USERNAME/buildcusnginx:v1.0.0
            kubectl get deploy,rs,svc,pods
          name: Deploy cluster

  create-service:
    docker:
      - image: python:3.7.3-stretch
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: ./service.yml
          resource-name: service/service-anh

  create-deployment:
    docker:
      - image: python:3.7.3-stretch
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: ./deployment.yml
          resource-name: deployment/deploy-anh

workflows:
  default:
    jobs:
      - build-lint
      - push-image-to-dockerhub:
          requires: 
            - build-lint
      - create-cluster:
          cluster-name: nginxcustomcluster
          requires:
            - push-image-to-dockerhub
      # - list-cluster:
      #     cluster-name: nginxcustomcluster
      #     requires:
      #       - create-cluster
      - create-service:
          cluster-name: nginxcustomcluster
          requires:
            #- list-cluster
            - create-cluster
      - create-deployment:
          cluster-name: nginxcustomcluster
          requires:
            - create-service
      - aws-eks/update-container-image:
          cluster-name: nginxcustomcluster
          container-image-updates: "newcontainer=$DOCKERHUB_USERNAME/buildcusnginx:v1.0.0"
          requires:
            - create-deployment
          resource-name: deployment/deploy-anh
      